### PR TITLE
Gauge flagging google

### PR DESCRIPTION
**Pull request by zackarno**
initial gauge flagging work to better understand how we might aggregate gauges.

Gauge data is retrieved from downloaded spreadsheet in this example. I am creating a new branch which will access it via googlesheets

### CODE REVIEW

**Comment by PaulineNimo** [comment]
Perhaps you didn't push the change yet but you need to also change the names of the objects when loading them from `nowcast` to `historical` in `hybas_exploration.Rmd`.

**Comment by zackarno** [comment]
> Perhaps you didn't push the change yet but you need to also change the names of the objects when loading them from `nowcast` to `historical` in `hybas_exploration.Rmd`.

Good catch!  fixed here [56b55eb](https://github.com/OCHA-DAP/pa-flood-pilot-validation/pull/2/commits/56b55eb729986d9859409bdc1d4dce59e3f40f85)

**Comment by caldwellst** [comment]
Will review once all of the other branches are merged into here as a single setup. For now will review the email output just for visual and design comments.

**Comment by zackarno** [comment]
> Will review once all of the other branches are merged into here as a single setup. For now will review the email output just for visual and design comments.

great - I am actually just going to close this PR as I've replaced it with one which merges everything up to this same point- plus adding some documentation/final steps

**Pull request closed without merging**
